### ISSUE TITLE
mailgun does not forward to kanboard

### ISSUE THREAD

**Issue by reiner** [kanboard/plugin-mailgun#11]
I am trying to integrate maligun but without luck so far. I feel I am almost there:
- everything entered in maligun mx settings work, etc.
- when I try to send to my kanban project, my mail server responds: 185.26.156.37 does not like recipient. sorry, this recipient is not in my validrcptto list (#5.7.1) 
- in mailgun the receiver address seems to be ok but when I enter the forwarding url I get a 200 error… do you have any idea how to solve it? I think sending emails as tasks would be tremendous more productive 

Do you have any idea? That would be very much appreciated! Thank you very much, Reiner

![route__list_-_mailgun](https://cloud.githubusercontent.com/assets/280713/18354095/b1cc0bac-75e4-11e6-9ce7-f404b243b1fa.jpg)

**Comment by fguillot** [comment]
The response 200 means that Mailgun is able to contact your Kanboard instance, so this part is working correctly.

However, your domain name "b2bsome.de" do not seems to have the proper MX records. They are not redirected to Mailgun servers. This is the reason why your email get rejected. At the moment, `b2bsome.de` point to `betelgeuse.uberspace.de`.
