### ISSUE TITLE
Incoming work but sending not

### ISSUE THREAD

**Issue by risturiz** [kanboard/plugin-mailgun#12]
Hi, i have mailgun configured and work great with incoming mail to create task... But i dont know why send email dont work.

> Application version: 1.0.35
> PHP version: 5.6.27-0+deb8u1
> PHP SAPI: fpm-fcgi
> OS version: Linux 2.6.32-44-pve
> Database driver: postgres
> Database version: 9.4.9
> Browser: Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0

I have debug active and dont show any error... Anyone have a hint for this?

Thanks.

**Comment by fguillot** [comment]
Unfortunately, your bug report do not give enough information to investigate anything.

Maybe you could try the latest version of the plugin with the latest version of Kanboard. The documentation has been updated as well in case you had some trouble with the configuration https://github.com/kanboard/plugin-mailgun#use-mailgun-to-send-emails
