### ISSUE TITLE
Problems with emails auto-forwarded from Gmail

### ISSUE THREAD

**Issue by akononykhin** [kanboard/plugin-mailgun#15]
Hello

If email if auto-forwarded to Mailgun from GMail where is one serious problem: Google modifies the sender address which will be placed into MAIL TO SMTP command (which is used by Mailgun to fill _sender_ parameter). So HTTP API request to Kanboard Mailgun plugin will contain unknown email.

For example if original address was `test@gmail.com` and it was forwarded to `kanboard+testprj@mg.mydomain.com` the final sender address will be 
`test+caf_=kanboard+testprj=mg.mydomain.com@gmail.com`
Kanboard knows about user with email `test@gmail.com` but knows nothing about `test+caf_=kanboard+testprj=mg.mydomain.com@gmail.com` so email is IGNORED.

I suggest a simple preg checking of sender email in EmailHandler.php validate() function:

diff EmailHandler.php EmailHandler.php.orig 
98,102d97
<         // If email is auto-forwarded from GMail it's necessary to 'clean' sender address
<         if(preg_match("/^(.*)\+caf\_[^@]*(.*)$/i", $payload['sender'], $matches)) {
<             $payload['sender'] = $matches[1].$matches[2];
<         }
< 

Best Regards
Alexey

**Comment by bugwatcher** [comment]
This issue has been closed automatically for inactivity after more than 1 year. Unfortunately, this project doesn't have enough resources to manage all these requests. [Read the FAQ](https://docs.kanboard.org/en/1.2.5/developer_guide/faq.html#why-do-you-close-inactive-issues-automatically).
