### ISSUE TITLE
How to use PHPunit

### ISSUE THREAD

**Issue by sebastiantiede** [kanboard/plugin-mailgun#2]
Can you give me a small introduction in testing plugins with PHPunit?
I don't get it!

**Comment by fguillot** [comment]
The current process is not optimal but at the moment I run the tests from the plugins folder of Kanboard.

- Copy or Clone or Symlink the repo in kanboard/plugins
- From the kanboard root folder, run the command `phpunit -c tests/units.sqlite.xml plugins/Mailgun/Test/`

**Comment by sebastiantiede** [comment]
mh, I get: 

``` 
Fatal error: Class 'Symfony\Component\Stopwatch\Stopwatch' not found in /Applications/MAMP/htdocs/…/kanboard/tests/units/Base.php on line 82
```
I tried to install Symfony Stopwatch to ```Kanboard/vendor/symfony/``` without effect
