### ISSUE TITLE
clarify setup

### ISSUE THREAD

**Issue by PatDeLux** [kanboard/plugin-mailgun#3]
Even with Mailgun reporting delivery of mail to my Kanboard, I can't get task creation via email working, so I have some questions.
Could you clarify the config.php parameters, specially the MAIL_FROM ?  
Let me give an (dummy) example:

- my normal mail is using domain sample.com, using Google Apps (Gmail)
- in Mailgun I have defined and verified domain mg.sample.com

I (patrick.h@sample.com) am defined with that email in my Kanboard.

Is MAIL_FROM used in Kanboard receiving tasks ? 
If yes, what address should be defined for MAIL_FROM ?

**Comment by jtourt** [comment]
MAIL_FROM is not used for receiving by the Mailgun plugin.

None of the Mailgun variables set in config.php are used for receiving -- they are used for sending only.

**Comment by PatDeLux** [comment]
Thanks. I reinstalled the latest version and works now.
