### ISSUE TITLE
New messages appears on default swimlane

### ISSUE THREAD

**Issue by bdrayer** [kanboard/plugin-mailgun#5]
Hi,

When creating a new task using Mailgun plugin, she is created on the default swimlane also if she is hided. It will be a good thing to allow to choose the swimlane (by example using an swimlane ID like for projects).

for example something+myproject+swimlane@mydomain.tld

Best regards

**Comment by fguillot** [comment]
I improved the code, to keep it simple the task is now created with in the first active swimlane.

**Comment by bdrayer** [comment]
Thanks a lot I will try
