### ISSUE TITLE
Setting up Email to Task

### ISSUE THREAD

**Issue by solstafir7** [kanboard/plugin-mailgun#9]
This might be a very stupid issue as I am very very new to this whole setup, but I want to know how to set up the forward address in mailgun.

I have added a route, so Mailgun properly picks up my incoming email and posts it to forward address. I have picked up the forward address from **Settings > Integrations > Mailgun**. It looks something like this,

http://<my.domain.tld>/mailgun/handler/XXXXXXXXXXXXXXXXXXXXXXXXX

Am I right in doing so? The docs mention some controller address. I didn't get it right. On that path, it says _'Internal Error: Controller not found'_

Secondly, How to exactly use the project identifier?

Is there any blog posts where the steps are detailed out?
Sorry for a very basic question. I didn't get the Kanboard configuration.

A great open source tool for Kanban btw, I have just started using it.

**Comment by fguillot** [comment]
I made a better documentation to configure Mailgun: https://kanboard.net/plugin/mailgun I hope that's help.

**Comment by solstafir7** [comment]
Thanks a lot. I will go through it right away.
